PAYLOADS = [
    'payload/windows/x64/custom/bind_ipv6_tcp',
    'payload/windows/x64/custom/bind_ipv6_tcp_uuid',
    'payload/windows/x64/custom/reverse_https',
    'payload/windows/x64/custom/reverse_named_pipe',
    'payload/windows/x64/custom/reverse_tcp_rc4',
    'payload/windows/x64/custom/reverse_tcp_uuid',
    'payload/windows/x64/custom/reverse_winhttp',
    'payload/windows/x64/custom/reverse_winhttps',
    'payload/windows/x64/meterpreter/bind_ipv6_tcp',
    'payload/windows/x64/meterpreter/bind_ipv6_tcp_uuid',
    'payload/windows/x64/meterpreter/bind_tcp',
    'payload/windows/x64/meterpreter/bind_tcp_rc4',
    'payload/windows/x64/meterpreter/bind_tcp_uuid',
    'payload/windows/x64/meterpreter/reverse_http',
    'payload/windows/x64/meterpreter/reverse_https',
    'payload/windows/x64/meterpreter/reverse_named_pipe',
    'payload/windows/x64/meterpreter/reverse_tcp',
    'payload/windows/x64/meterpreter/reverse_tcp_rc4',
    'payload/windows/x64/meterpreter/reverse_tcp_uuid',
    'payload/windows/x64/meterpreter/reverse_winhttp',
    'payload/windows/x64/meterpreter/reverse_winhttps',
    'payload/windows/x64/pingback_reverse_tcp',
    'payload/windows/x64/powershell_bind_tcp',
    'payload/windows/x64/powershell_reverse_tcp',
    'payload/windows/x64/powershell_reverse_tcp_ssl',
    'payload/windows/x64/shell/bind_ipv6_tcp',
    'payload/windows/x64/shell/bind_tcp',
    'payload/windows/x64/shell/bind_tcp_rc4',
    'payload/windows/x64/shell/bind_tcp_uuid',
    'payload/windows/x64/shell/reverse_tcp',
    'payload/windows/x64/shell/reverse_tcp_rc4',
    'payload/windows/x64/shell/reverse_tcp_uuid',
    'payload/windows/x64/shell_bind_tcp',
    'payload/windows/x64/shell_reverse_tcp',
    'payload/windows/x64/vncinject/bind_ipv6_tcp',
    'payload/windows/x64/vncinject/bind_ipv6_tcp_uuid',
    'payload/windows/x64/vncinject/bind_named_pipe',
    'payload/windows/x64/vncinject/bind_tcp',
    'payload/windows/x64/vncinject/bind_tcp_rc4',
    'payload/windows/x64/vncinject/bind_tcp_uuid',
    'payload/windows/x64/vncinject/reverse_http',
    'payload/windows/x64/vncinject/reverse_https',
    'payload/windows/x64/vncinject/reverse_tcp_rc4',
    'payload/windows/x64/vncinject/reverse_tcp_uuid',
    'payload/windows/x64/vncinject/reverse_winhttp',
]


def get_random_payload(r):
    rand_index = r.randint(0, len(PAYLOADS)-1)
    return PAYLOADS[rand_index].replace("payload/", "")
